#!/bin/bash

### g09td2csv
### Script to obtain transition energies and intensities from Gaussian09 TD calculation
### Export data in CSV (Comma-Separated Values)
### Grupo de Espectroscopia Teórica e Modelagem Molecular - GETMM (IQ/UFRJ)
### Author Carlos Eduardo Vieira de Moura : carlosevmoura@iq.ufrj.br

## Checking Gaussian09 log file
if [ -n "$1" ]; then
	if [ -f "$1" ]; then
		LOG=$1
	else
		echo -e "\033[01;31m$1 Gaussian09 log file was not found.\033[00m"
		exit 1
	fi
else
	echo -e "Usage: g09td2csv [Gaussian09 log file]"
	exit 1
fi

if grep -q "Normal termination of Gaussian 09" "$LOG"; then
    if grep -q "Excited State" "$LOG"; then		
		FILENAME=$(basename "$LOG")
		FILENAME="${FILENAME%.*}"
    fi
else
	echo -e "\033[01;31mGaussian09 log aren't from TD type. End of script execution.\033[00m"
	exit 1
fi

## Obtaining TD data from log file
grep "Excited State" $LOG |awk '{print $5}' > .energy.temp
grep "Excited State" $LOG |awk '{print $9}'|cut -f 2 -d '=' > .oos.temp

## Building CSV file
touch $FILENAME.td.csv
echo "Transition Energy (eV),Oscillator Strength" > $FILENAME.td.csv
paste -d "," .energy.temp .oos.temp >> $FILENAME.td.csv

## Removing temporary files
rm -f .temp1 .temp2

## Finishing script
echo -e "\033[01;32m$FILENAME.td.csv preview:\033[00m"
cat $FILENAME.td.csv
echo -e "\033[01;32mg09td2csv was sucesfully executed.\033[00m"
